Blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views


app_name = "Blog"

urlpatterns=[
    url(r'^settings/$', views.settings, name="settings"),
    
]

urlpatterns+=[
	path('', views.index, name='index'),
    path('blogDetail/(?P<blogId>\d+)/', views.blogDetail, name='blogDetail'),
    path('new_post/', views.new_post, name='new_post'),


    path('edit_post/<blogpost_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<blogpost_id>/', views.delete_post, name='delete_post'),


    path('edit_post/<blogpost_id>', views.edit_post, name='edit_post'),
    path('delete_post/<blogpost_id>', views.delete_post, name='delete_post'),
    path('simple_search/', views.simple_search, name='simple_search'),
    path('like_post/', views.like_post, name='like_post'),
    path('dislike_post/', views.dislike_post, name='dislike_post'),
    path('notifications/', views.notifications, name='notifications'),
]

Query/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .import views

app_name = "Query"
urlpatterns=[
    url(r'^RetaurantandBar', views.RetaurantandBar, name='RetaurantandBar'),
    url(r'^placeDetail/rest/(?P<placeId>\d+)/',views.restDetail,name= 'restDetail'),
    url(r'^placeDetail/place/(?P<placeId>\d+)/',views.placeDetail,name= 'placeDetail'),
    url(r'^result/$',views.result,name= 'result'),
    url(r'^soo/$',views.soo,name= 'soo'),
    url(r'^map/$',views.map,name= 'map'),
]

urlpatterns+=[
	url(r'^logout$',auth_views.logout, {'template_name':'Query/logout.html'},name="logout" ),
    url(r'^$',auth_views.login, {'template_name':'Query/index.html'},name="login" ),
    url(r'^register/$', views.register, name="register"),
    url(r'^home/$',views.index,name="home" ), #recommendations returned from Query.views.index

]

SmartTravel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('Blog.urls',  namespace='Blog')),
    url(r'^', include('Query.urls', namespace='Query')),
   	
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()
    date_pub = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_public=models.BooleanField(default=True)
    photo=models.FileField( null=True, blank=True)

    likes = models.PositiveIntegerField(default=0)
    dislikes = models.PositiveIntegerField(default=0)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date_pub',)

    def __str__(self):
        '''Returns string representation of BlogPost model'''
        return self.title[:50]

class BlogLike(models.Model):
    ''''''
    blogPost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class BlogDislike(models.Model):
    ''''''
    blogPost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class BlogComment(models.Model):
    ''''''
    content = models.TextField()
    date_pub = models.DateTimeField(auto_now_add=True)
    blogPost = models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date_pub',)

    def __str__(self):
        '''Returns string representation of BlogComment model'''
        return "Comment by {} on {}".format(self.owner, self.blogPost)


class Notification(models.Model):
    owner = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=200)
    blogPost = models.ForeignKey(BlogPost, on_delete=models.CASCADE, null=True)
    client = models.ForeignKey(User, related_name='client', on_delete=models.CASCADE, null=True )
    created = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.content[:50]


class Blog_Search(models.Model):
    search_name=models.CharField(max_length=30) # kaslai search gareko
    viewer_id=models.IntegerField() # kasle search gareko
    searched_date = models.DateTimeField(auto_now_add=True)

Blog/forms.py
from django import forms

from .models import BlogPost, BlogComment

class BlogPostForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write title...',
        }
    ))

    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write content...',
        }
    ))
    photo=forms.FileField(widget=forms.FileInput())

    # is_public = forms.BooleanField(widget=forms.CheckboxInput(
    #     attrs={
    #
    #     }
    # ))

    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'is_public', 'photo']



class BlogCommentForm(forms.ModelForm):

    content = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write comment...',
        }
    ))

    class Meta:
        model = BlogComment
        fields = ('content',)

Blog/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect
from django.urls import reverse
from django.http import Http404, JsonResponse
import os
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import *
from .forms import BlogPostForm, BlogCommentForm
from .simple_search import get_query

# Create your views here.

def settings(request):
    template_path = "Blog/settings.html"
    return render(request, template_path)

# Create your views here.
def index(request):

    blogPosts = BlogPost.objects.order_by('-date_pub')

    page = request.GET.get('page', 1)

    paginator = Paginator(blogPosts, 5)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    context = {'blogPosts': blogs}

    template_path="Blog/index.html"
    return render(request, template_path, context)


def blogDetail(request, blogId):

    blog = BlogPost.objects.get(id=blogId)

    comments = blog.comments.filter(active=True).order_by('-date_pub')

    if request.method != 'POST':
        comment_form = BlogCommentForm()
    else:
        comment_form = BlogCommentForm(data = request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.blogPost = blog
            new_comment.owner = request.user
            new_comment.save()

            #notification
            content = "commented on your blogpost"
            new_notification = Notification(owner=blog.owner, content=content, client=request.user, blogPost=blog)
            new_notification.save()

    context = {'blog': blog, 'comment_form': comment_form, 'comments': comments}
    return render(request, 'Blog/blogDetail.html', context)


@login_required()
def new_post(request):
    '''Create a new post'''
    if(request.method != 'POST'):
        form = BlogPostForm()
    else:
        form = BlogPostForm(request.POST, request.FILES)
        if(form.is_valid()):
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()

            # notification
            content = "created a new blogpost"
            new_notification = Notification(owner=new_post.owner, content=content, client=request.user,
                                            blogPost=new_post)
            new_notification.save()

            return HttpResponseRedirect(reverse('Blog:index'))

    context = {'form': form}
    return render(request, 'Blog/new_post.html', context)

@login_required
def edit_post(request, blogpost_id):
    '''Edit an existing post'''
    blogpost = BlogPost.objects.get(id=blogpost_id)
    if(blogpost.owner != request.user):
        raise Http404

    title = blogpost.title
    content = blogpost.content
    is_public = blogpost.is_public
    photo = blogpost.photo

    if request.method != 'POST': #get http request ...occurs when loading edit mode
        form = BlogPostForm(instance=blogpost)
        
    else: #when submitting the edited form 
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()

            # notification
            content = "edited your blogpost"
            new_notification = Notification(owner=blogpost.owner, content=content, client=request.user,
                                            blogPost=blogpost)
            new_notification.save()

            return HttpResponseRedirect(reverse('Blog:index'))

    context = {'form': form, 'blogpost': blogpost}
    return render(request, 'Blog/edit_post.html', context)


@login_required
def delete_post(request, blogpost_id):

    blogpost = BlogPost.objects.get(id=blogpost_id)

    if(blogpost.owner != request.user):
        raise Http404
    else:
        # notification
        content = "deleted your blogpost \"%s\"" % (blogpost.title)
        new_notification = Notification(owner=request.user, content=content, client=request.user, blogPost=None)
        new_notification.save()

        blogpost.delete()

    return redirect('Blog:index')


def simple_search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']

        entry_query = get_query(query_string, ['title', 'content', ])

        found_entries = BlogPost.objects.filter(entry_query).order_by('-date_pub')

        context = {'query_string': query_string, 'found_entries': found_entries}
    return render(request, 'Blog/search_results.html', context)


@login_required()
def like_post(request):
    blogpost_id = None
    if(request.method == 'GET'):
        blogpost_id = request.GET['blogpost_id']

    likes=0;    dislikes = 0;
    if(blogpost_id):
        blogpost = BlogPost.objects.get(id=int(blogpost_id))
        if(blogpost):
            if(request.user.bloglike_set.filter(blogPost=blogpost).count()<1):  #Like
                blogLike = BlogLike(blogPost=blogpost, user=request.user)
                blogLike.save()
                likes = blogpost.bloglike_set.all().count()
                request.user.blogdislike_set.filter(blogPost=blogpost).delete()

                # notification
                content = "liked your blogpost"
                new_notification = Notification(owner=blogpost.owner, content=content, client=request.user,
                                                blogPost=blogpost)
                new_notification.save()

            else:   #Unlike
                request.user.bloglike_set.filter(blogPost=blogpost).delete()
                likes = blogpost.bloglike_set.all().count();

                # notification
                content = "unliked your blogpost"
                new_notification = Notification(owner=blogpost.owner, content=content, client=request.user,
                                                blogPost=blogpost)
                new_notification.save()

            dislikes = blogpost.blogdislike_set.all().count();

    '''Return JSON'''
    data = {'likes': likes, 'dislikes': dislikes}
    return JsonResponse(data);

@login_required()
def dislike_post(request):
    blogpost_id = None
    if (request.method == 'GET'):
        blogpost_id = request.GET['blogpost_id']

    dislikes = 0
    likes = 0
    if (blogpost_id):
        blogpost = BlogPost.objects.get(id=int(blogpost_id))
        if (blogpost):
            if (request.user.blogdislike_set.filter(blogPost=blogpost).count()<1):
                blogDislike = BlogDislike(blogPost=blogpost, user=request.user)
                blogDislike.save()
                dislikes = blogpost.blogdislike_set.all().count()
                request.user.bloglike_set.filter(blogPost=blogpost).delete()

            else:
                request.user.blogdislike_set.filter(blogPost=blogpost).delete()
                dislikes = blogpost.blogdislike_set.all().count()
            likes = blogpost.bloglike_set.all().count()

    data = {'likes': likes, 'dislikes': dislikes}
    return JsonResponse(data);


@login_required()
def notifications(request):

    #notis = request.user.notification_set.filter(is_read=False).order_by('-created')
    notis = Notification.objects.filter(owner=request.user).order_by('-created')

    context = {'notifications': notis}
    return render(request, 'Blog/notifications.html', context)

Blog/templates/Blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home </title>


    <!-- AJAX jquery script source-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'  %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog-home.css' %} " rel="stylesheet">
    <script src="{% static 'js/blog-home.js' %} "></script>

  </head>
  <body style="background-color:#eaebed;">

            <!-- Modal-->
                    <div class="modal fade" id="Sign_In_Modal" role="dialog">
                    <div class="modal-dialog ">

                      <!-- Modal content-->
                      <div class="modal-content" style=" background-color: #e8e6ef; padding: 10px; margin: auto; width: 130%; border: 1px solid #767b7f; border-radius:3%;">
                        <div class="modal-header" style="color: black;"> Explore our recommendations and write your own blogs. </div>
                          
                          <!-- corousel in sign in modal -->
                          <div class="container">
                              <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                                <div class="carousel-inner">
                                  <div class="carousel-item active">
                                    <img class="d-block" src="/media/restaurant/Dalle.png" style=" border: 3px solid #767b7f; border-radius: 2%; margin: auto; height: 300px; width:auto;" alt="First slide">
                                  </div>
                                  <div class="carousel-item">
                                    <img class="d-block" src="/media/restaurant/OR2K.jpg" style=" border: 3px solid #767b7f; border-radius: 2%;  margin:auto; height: 300px; width:auto;" alt="Second slide">
                                  </div>
                                  <div class="carousel-item">
                                    <img class="d-block" src="/media/restaurant/Melrose_Restaurant___Bar.jpg" style=" border: 3px solid #767b7f; border-radius: 2%;  margin: auto; height: 300px; width:auto;" alt="Third slide">
                                  </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                  <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                  <span class="sr-only">Next</span>
                                </a>
                              </div>
                          </div>
                            <!-- corousel ends here -->
                            <hr>
                          <form method="POST" action="{% url 'Query:login' %}" >
                             {% csrf_token %}
                            <div class="form-group container">
                              <label style="color: black;">Username</label>
                              <input type="text" name="username" style="color: black;" class="form-control" id="username" aria-describedby="help" placeholder="Enter username">
                              <small id="help" class="form-text text-muted">That's a good one.</small>
                            </div>
                            
                            <div class="form-group container">
                              <label style="color: black;">Password</label>
                              <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                            </div>
                            <button type="submit" class="btn btn-success container">Okay Go!</button>
                          </form>
                          <a href="#" data-dismiss="modal" style="margin:auto; padding: 10px; float=center; color: #06599e;">No thanks!</a>
                      </div>
                    </div>
                </div>
              </div>
          </div>
      
      <!-- end of sign in form  -->



   
    <div class="container bg-light">

      <!-- nav bar starts  -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
              <a href="#" onclick="openNav();" ><img id="profile"  class="card-img-left border" src="{% static 'images/shristi.jpg' %}" style="width:56px; border-radius: 50%" alt="profile" ></a>
              
              <!-- for three line button when window size is smaller -->
              <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-expanded controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <!-- for top-right nav bar -->
              <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto" id="top_nav_bar">

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'Query:home'%}">Home
                      <span class="sr-only"> (current)</span>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="/blog">Blog</a>
                  </li>
                                   
                  {% if not user.is_authenticated %}
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'Query:register' %}"><b>SignUp</b></a><!-- back to blog/index.html page-->
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link" data-toggle="modal" data-target="#Sign_In_Modal">SignIn</button>
                    </li>                      
                    {% else %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'Query:logout' %}"><b>LogOut</b></a><!-- back to blog/index.html page-->
                      </li>
                      <li class="nav-item">
                        <a class="nav-link">{ {{ user.username }} }</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'Blog:notifications' %}">Notifications</a>
                      </li>
                      
                    {% endif %}
                </ul>
              </div>
            </div>
          </nav>
      <!-- nav bar ends  -->


    <div style="margin-top:20px; padding:2px;">
      {% block new_post %}{% endblock %}
      {% block content %}{% endblock %}
    </div>
      
        {% block blog_content %}{% endblock %}
    </div>
    
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script> 

  </body>
</html>

Blog/templates/Blog/edit_post.html
{% extends 'Blog/base.html' %}

{% block header %}

    <br>
	<h4 class="lead">Edit your blog post:</h4>
	<hr class="my-4">

{% endblock header %}

{% block content %}

    <form action="{% url 'Blog:edit_post' blogpost.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" class="btn btn-success">Save Changes</button>
    </form>

{% endblock content %}

Blog/templates/Blog/extra.html
<!-- Sidebar Widgets Column -->
        <div class="col-md -4">

          <!-- Search Widget -->
          <div class="card bg-light ">
            <div class="card-body">
              <div class="input-group">
                <form method="get" action="{% url 'Blog:simple_search' %}" accept-charset="utf-8" class="form-inline my-2 my-lg-0">
      					<input type="search" name="q" placeholder="Search blog" aria-label="Search" class="form-control">
      					<button type="submit" class="btn btn-outline-success">Search</button>
      				</form>
              </div>
            </div>
          </div>

        </div>


        {% for blog in blogPosts %}
            {% if blog.photo %}
              <!-- Blog Posts -->
              
              <div class="card " style="background-color: #e8e5e5; padding: 3px; margin: 2px; border-radius: 3%;">
                <img class="card-img-top" src="{{blog.photo.url}}" alt="Card image cap" style="width:300px; border-radius: 3%; height:auto;">
                
                <div class="card-body">
                  <h4 class="card-title">{{ blog.title }}</h4>
                  <p class="card-text inline">{{ blog.content|truncatechars:50 }}</p>
                  <a href="{% url 'Blog:blogDetail' blog.id %}" class="btn btn-primary">Read More &rarr;</a>

                  {% if blog.owner == user %}
                    <a href="{% url 'Blog:edit_post' blog.id %}" class="btn btn-primary card-link">Edit Post &rarr;</a>
                    
                    <!-- delete confirmation Modal -->
                    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Are You Sure?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <a href="{% url 'Blog:delete_post' blog.id %}"  class="btn btn-default"><span class="glyphicon glyphicon-remove">Delete</span></a>
                          </div>
                        </div>
                      </div>
                    </div>

                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#DeleteModal">
                     Delete
                    </button>

                  {% endif %}
                </div>
                <div class="card-footer text-muted">
                  Posted on {{ blog.date_pub.date }} by
                  <a href="#">{{ blog.owner }}</a>
                </div>
              </div>
            {% endif %}
            <hr>
            {% endfor %}

Blog/templates/Blog/index.html
{% extends 'Blog/base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block blog_content %}

<div class="container">

    <!-- sidenav-->
    <div id="mySidenav" class="sidenav ">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="#">Profile</a>
        <a href="#">Your Blog</a>
        <a href="#">Tour Diary </a>
        <a href="#">Followers</a>
        <a href="#">Followings</a>
    </div>


<div id="main">

      <!--new post-->
      <p><a class="btn btn-outline-primary" href="{% url 'Blog:new_post' %}">Create New Post</a></p>

      <!-- Project Four -->

      {% for blog in blogPosts %}
      {% if blog.photo %}
      <div class="row container" style="color: #20222b; margin:none; padding: none; border-radius:4%; border: 1px solid #d0d1d8">
        <div class="col-md-7">
          <a href="{{blog.photo.url}}">
            <img class="card-img-top" src="{{blog.photo.url}}" alt="Card image cap" style="width:500px; border-radius:4%; margin:none; padding:none; height:auto;">
          </a>
        </div>
        <div class="col-md-5" style=" padding:2%; margin-top:2px">
          <a  class="card-title h4" href="{% url 'Blog:blogDetail' blog.id %}" >{{ blog.title }}</a>
          <p class="card-text inline" style="height: 66%; padding:1px;">{{ blog.content|truncatechars:100}}</p>

           {% if blog.owner == user %}
           <!-- delete trigger -->
          <a href="#" class="card-link" data-toggle="modal" data-target="#DeleteModal">Delete</a>
          <!-- edit ref -->
          <a href="{% url 'Blog:edit_post' blog.id %}" class="card-link">Edit Post &rarr;</a>
          {% endif %}
                                              
              <!-- delete confirmation Modal -->
              <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalCenterTitle">Are You Sure?</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      <a href="{% url 'Blog:delete_post' blog.id %}"  class="btn btn-default"><span class="glyphicon glyphicon-remove">Delete</span></a>
                    </div>
                  </div>
                </div>
              </div>

              <div class="text-muted">
                  Posted {{ blog.date_pub|naturaltime }} by
                  <a href="#">{{ blog.owner }}</a>
              </div>
            </div>
        </div>
        <!-- /.card -->
         <hr>
       {% endif %}
      {% endfor %}
      


        <!-- Pagination -->
        {% if blogPosts.has_other_pages %}
          <ul class="pagination justify-content-center mb-4">

            {% if blogPosts.has_previous %}

                {% if blogPosts.paginator.num_pages > 5 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ 1 }}">First</a>
                    </li>
                {% endif %}

              <li class="page-item">
                <a class="page-link" href="?page={{ blogPosts.previous_page_number }}">&laquo; Newer</a>
              </li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
            {% endif %}


          {% for i in blogPosts.paginator.page_range %}
              {% if i <= blogPosts.number|add:5 and i >= blogPosts.number|add:-5 %}
                  {% if blogPosts.number == i %}
                      <li class="page-item active"><span class="page-link">{{ i }}<span class="sr-only">(current)</span></span></li>
                  {% else %}
                      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                  {% endif %}
              {% endif %}
          {% endfor %}


            {% if blogPosts.has_next %}
              <li class="page-item ">
                <a class="page-link" href="?page={{ blogPosts.next_page_number }}">Older &raquo;</a>
              </li>

                {% if blogPosts.paginator.num_pages > 5 %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ blogPosts.paginator.num_pages }}">Last</a>
                    </li>
                {% endif %}

            {% else %}
              <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
            {% endif %}

          </ul>
       {% endif %}

  </div>
  <!-- main ends  -->
</div>
<!-- container ends  -->
{% endblock %}

Blog/templates/Blog/new_post.html
{% extends 'Blog/base.html' %}

{% block new_post %}


    <br>
	<h4 class="lead">Create a new post:</h4>
	<hr class="my-4">

{% endblock %}

{% block content %}

    <div class="jumbotron">
	<form action="{% url 'Blog:new_post' %}"  enctype='multipart/form-data' method="post" class="form">
		{% csrf_token %}
		{{ form.as_p }}

		<button class="btn btn-primary" name="submit">add post</button>

	</form>
    </div>

{% endblock %}

Blog/templates/Blog/search_results.html
{% extends 'Blog/base.html' %}

{% block header %}
	<hr class="my-4">
	<h3 class="lead">Search results for "{{ query_string }}"" :</h3>
	<hr class="my-4">
{% endblock header %}

{% block content %}

	{% for blogpost in found_entries %}
		<div class="card bg-light mb-3">
			<div class="card-header">
				<small>{{ blogpost.date_pub }}</small>
			</div>
			<div class="card-body">
				<h3 class="card-title text-primary">
					{{ blogpost.title }}
				</h3>
				<div class="card-text text-secondary">
					{{ blogpost.content|truncatechars:50 }}
				</div>

                <a class="card-link" href="{% url 'Blog:blogDetail' blogpost.id %}">Read more</a>
				<a class="card-link" href="{% url 'Blog:edit_post' blogpost.id %}">edit post</a>
                <a class="card-link" href="{% url 'Blog:delete_post' blogpost.id %}">delete post</a>
			</div>
		</div>
	{% empty %}
		<h4 class="lead">Cannot find any results.</h4>
	{% endfor %}

{% endblock content %}

Blog/templates/Blog/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Settings</title>
</head>
<body>

</body>
</html>