Blog/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views


app_name = "Blog"

urlpatterns=[
    url(r'^settings/$', views.settings, name="settings"),
    
]

urlpatterns+=[
	path('', views.index, name='index'),
    path('blogDetail/(?P<blogId>\d+)/', views.blogDetail, name='blogDetail'),
    path('new_post/', views.new_post, name='new_post'),


    path('edit_post/<blogpost_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<blogpost_id>/', views.delete_post, name='delete_post'),


    path('edit_post/<blogpost_id>', views.edit_post, name='edit_post'),
    path('delete_post/<blogpost_id>', views.delete_post, name='delete_post'),
    path('simple_search/', views.simple_search, name='simple_search'),
    path('like_post/', views.like_post, name='like_post'),
    path('dislike_post/', views.dislike_post, name='dislike_post'),
    path('notifications/', views.notifications, name='notifications'),
]

Query/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .import views

app_name = "Query"
urlpatterns=[
    url(r'^RetaurantandBar', views.RetaurantandBar, name='RetaurantandBar'),
    url(r'^placeDetail/rest/(?P<placeId>\d+)/',views.restDetail,name= 'restDetail'),
    url(r'^placeDetail/place/(?P<placeId>\d+)/',views.placeDetail,name= 'placeDetail'),
    url(r'^result/$',views.result,name= 'result'),
    url(r'^soo/$',views.soo,name= 'soo'),
    url(r'^map/$',views.map,name= 'map'),
]

urlpatterns+=[
	url(r'^logout$',auth_views.logout, {'template_name':'Query/logout.html'},name="logout" ),
    url(r'^$',auth_views.login, {'template_name':'Query/index.html'},name="login" ),
    url(r'^register/$', views.register, name="register"),
    url(r'^home/$',views.index,name="home" ), #recommendations returned from Query.views.index

]

SmartTravel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('Blog.urls',  namespace='Blog')),
    url(r'^', include('Query.urls', namespace='Query')),
   	
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Query/models.py
from django.db import models
from django.db.models import Q

class PlaceDetail(models.Model):
    Name = models.CharField(max_length=200, null=True)
    Desc = models.CharField(max_length=3500, null=True)
    Opening_Time = models.CharField(max_length=30,default="Always open")
    Entry_fee = models.CharField(max_length=30,default=0)
    C_Name = models.CharField(max_length=300, null=True)
    latitude = models.CharField(max_length=50 , null=True)
    longitude = models.CharField(max_length=50 , null=True)
    Img_Path = models.CharField(max_length=300 , null=True)
    Popularity = models.CharField(max_length=10 , null=True)
    P_Name = models.CharField(max_length=50 , null=True)
    District = models.CharField(max_length=50 , null=True)
    Zone = models.CharField(max_length=50 , null=True)
    photo=models.FileField(upload_to='place', null=True, blank=True)
   
    likes = models.PositiveIntegerField(default=13)
    date_pub = models.DateTimeField(auto_now_add=True, null=True, blank=True)

class RestDetail(models.Model):
    Name = models.CharField(max_length=50)
    Desc = models.CharField(max_length=3000, null=True)
    Opening_Time = models.CharField(max_length=30,default="Always open")
    Contact_No = models.CharField(max_length=20)
    Popular_for = models.CharField(max_length=1000)
    C_Name = models.CharField(max_length=50)
    latitude = models.CharField(max_length=50)
    longitude = models.CharField(max_length=50)
    Img_Path = models.CharField(max_length=100)
    P_Name = models.CharField(max_length=300)
    District = models.CharField(max_length=50)
    Zone = models.CharField(max_length=50)
    charge=models.CharField(max_length=200)
    photo=models.FileField(upload_to='restaurant', null=True, blank=True)
   
    likes = models.PositiveIntegerField(default=13)
    date_pub = models.DateTimeField(auto_now_add=True, null=True, blank=True)

Query/forms.py
from django import forms
from django.contrib.auth.models import User

#Signup
class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        required = True,
        label = 'Username',
        max_length = 32
    )
    email = forms.CharField(
        required = True,
        label = 'Email',
        max_length = 32,
    )
    password = forms.CharField(
        required = True,
        label = 'Password',
        max_length = 32,
        widget = forms.PasswordInput()
    )   

Query/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404, redirect, reverse
from .models import PlaceDetail, RestDetail
from django.db.models import Q
import collections
from .RegularExpReplacer import Query
import cloudinary
import cloudinary.uploader
import cloudinary.api
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .forms import UserRegistrationForm
from django.contrib.auth.forms import UserCreationForm
import os, csv


from .save import * 
def soo(request):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    filename=os.path.join(BASE_DIR, "Query/restaurants_and_cafe_with_lat_lng.csv")
    data=save(filename )
    run(data)
    return HttpResponseRedirect('/blog/')

cloudinary.config(
  cloud_name = "ddfo4jcn7",
  api_key = "276479899713558",
  api_secret = "gFy1KH-zxzud7fKzohWVbmk-eHM"
)

r1 = ['F', 'PV', 'N']
r2 = ['F', 'N']
r3 = ['PV', 'N']
r4 = ['F', 'PV', 'D']
r5 = ['PV', 'D']
r6 = ['F', 'R', 'N']
r7 = ['R', 'N']
r8 = ['R', 'D']
r9 = ['F', 'L', 'N']
r11 = ['L', 'N']
r10 = ['F', 'L', 'D']
r12 = ['L', 'D']
r13 = ['WH', 'NE']
r14 = ['F', 'H', 'PA', 'N']
r15 = ['F', 'H', 'PA', 'D']
r16 = ['H', 'PA', 'D']
r17 = ['H', 'PA', 'N']
r18 = ['PV', 'F', 'HU', 'D']
r19 = ['PV', 'F', 'HU', 'N']
r20 = ['PV', 'HU', 'N']
r21 = ['PV', 'HU', 'D']
r22 = ['WH', 'HU', 'N']
r23 = ['WH', 'HU', 'D']
r24 = ['F', 'PV', 'C', 'N']
r25 = ['WH', 'C', 'N']
r26 = ['F', 'PV', 'C', 'D']
r27 = ['WH', 'C', 'D']
r28 = ['C', 'D']
r29 = ['C', 'N']
r30 = ['F', 'PV', 'RA', 'N']
r31 = ['WH', 'RA', 'N']
r32 = ['F', 'PV', 'RA', 'D']
r33 = ['WH', 'RA', 'D']
r34 = ['RA', 'D']
r35 = ['RA', 'N']
r36 = ['F', 'PV', 'T', 'N']
r37 = ['WH', 'T', 'N']
r38 = ['F', 'PV', 'T', 'D']
r39 = ['WH', 'T', 'D']
r40 = ['T', 'D']
r41 = ['T', 'N']
r42 = ['F', 'PV', 'PG', 'N']
r43 = ['WH', 'PG', 'N']
r44 = ['F', 'PV', 'PG', 'D']
r45 = ['WH', 'PG', 'D']
r46 = ['PG', 'D']
r47 = ['PG', 'N']
r48 = ['F', 'PV', 'B', 'N']
r49 = ['WH', 'B', 'N']
r50 = ['F', 'PV', 'B', 'D']
r51 = ['WH', 'B', 'D']
r52 = ['B', 'D']
r53 = ['B', 'N']
r54 = ['F', 'H', 'PV', 'N']
r55 = ['PV', 'H', 'N']
r56 = ['F', 'H', 'HH', 'N']
r57 = ['H', 'HH', 'N']
r58 = ['F', 'H', 'PV', 'D']
r59 = ['PV', 'H', 'D']
r60 = ['F', 'H', 'HH', 'D']
r61 = ['H', 'HH', 'D']
r62 = ['NA', 'N']
r63 = ['NA', 'D']
r64 = ['PA', 'NL']
r65 = ['F', 'TE', 'N']
r66 = ['TE', 'N']
r67 = ['RE', 'N', 'PV']
r68 = ['F', 'TE', 'D']
r69 = ['TE', 'D']
r70 = ['F','M','AR','D']

#compares two list

compare = lambda x, y: collections.Counter(x) == collections.Counter(y)

#views here
story = ""

template_Name =None
template_Name1 = None
category =None

class myQuery():
    def __init__(self):
        self.category=None
        self.category1=None
        self.category2=None

q1 = myQuery()
types_of_encoding = ["utf8", "cp1252"]
def soo(request):
    path="C:/Users/Deepika/SmartTravel/Query"
    os.chdir(path)
    with open("trekking1.csv",encoding='utf-8',errors='replace') as csvfile:
        reader=csv.DictReader(csvfile)
        for row in reader:
            p=PlaceDetail(Name=row['P_Name'], Desc=row['Desc'],Opening_Time='According to Season',C_Name=row['Category'], latitude=row['Latitude'], longitude=row['Longitude'], Img_Path="/media/restaurant/"+row['img_path'], Popularity=row['Popular_for'], P_Name=row['locality'], District=row['Zone'], Zone=row['District'],Entry_fee=row['Charge_Per_Head'])
            p.save()
            print("Success")
    return HttpResponseRedirect('/blog/')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def index(request):
    template_Name='Query/index.html'
    context={}
    res1=[]
    res2=[]
    res3=[]
    user=request.user
    data=readingFile1(os.path.join(BASE_DIR, "Query/result2.csv"))
    for res in data:
        if res.__getitem__(0)==user.id and res.__getitem__(2)>3.0: # 0 for user_id , 1 for place id and 3 for rating 
            res1.append(res.__getitem__(1)) #store place id ranked higher than 3 by user
            if(PlaceDetail.objects.filter(id=res.__getitem__(1)).exists()):
                q1.category1='P'
                place_det=PlaceDetail.objects.get(id=res.__getitem__(1))
                res2.append(place_det) # esma chai places ko details basxa
            if(RestDetail.objects.filter(id=res.__getitem__(1)).exists()):
                q1.category2='R'
                rest=RestDetail.objects.get(id=res.__getitem__(1))
                res3.append(rest)  # esma chai restaurant hruko kinavane hamisnga duita diffrent db hunx 
            
     
    context['places_recommendations']=res2
    context['rest_recommendations']=res3
    return  render(request,template_Name, context)


def readingFile1(filename):
    f = open(filename,"r")
    data = []
    for row in f:
        r = row.split(',')
        e = [int(r[0]), int(r[1]), float(r[2])]
        data.append(e)
    return sorted(data)



def result(request):
        query_search = request.GET.get('place',None)

        q=Query()
        q.makefile()
        to_lower = query_search.lower()

        result = q.Process_Query(to_lower)
        list1 = ['CH','DI','RE','ST']

        bool_value = True
        print(result)
        for tag_words in result:
            if tag_words in list1:
                bool_value = False

        if(bool_value):
            category='P'
            q1.category='P'
            template_Name = 'Query/query_result.html'
            if compare(result,r1) or compare(result,r3):
                Place_Name = PlaceDetail.objects.filter(Popularity__gt='3')
            elif compare(result,['D']):
                Place_Name = PlaceDetail.objects.filter(Popularity__gt='3')
            elif compare(result,r2):
                Place_Name= PlaceDetail.objects.filter(Popularity__gt='3')
            elif compare(result,r4) or compare(result,r5):
                res1 = q.get_tag_name('D')
                Place_Name =PlaceDetail.objects.filter(District__icontains = res1)
            elif compare(result,['A','REL','PV','N']) or compare (result,['F','A','REL','PV']) or compare (result,['A','REL','PV']):
                res1 = q.get_tag_name('A')
                res2 = q.get_tag_name('REL')
                Place_Name = PlaceDetail.objects.filter(Q(C_Name__icontains=res1) | Q(C_Name__icontains=res2))
            elif compare(result,['A','REL','PV','D']) or compare (result,['F','A','REL','PV','D']) or compare (result,['A','REL','PV','D']):
                res1 = q.get_tag_name('A')
                res2 = q.get_tag_name('REL')
                res3 = q.get_tag_name('D')
                Place_Name = PlaceDetail.objects.filter(Q(C_Name__icontains=res1) | Q(C_Name__icontains=res2),District__icontains= res3)
            elif compare(result,['T','REL','PV','D']) or compare (result,['F','T','REL','PV','D']) or compare (result,['T','REL','PV','D']):
                res1 = q.get_tag_name('T')
                res2 = q.get_tag_name('REL')
                res3 = q.get_tag_name('D')
                Place_Name = PlaceDetail.objects.filter(Q(C_Name__icontains=res1) | Q(C_Name__icontains=res2),District__icontains=res3)
            elif compare(result,['T','REL','PV','N']) or compare (result,['F','T','REL','PV','N']) or compare (result,['T','REL','PV']):
                res1 = q.get_tag_name('T')
                res2 = q.get_tag_name('REL')
                Place_Name = PlaceDetail.objects.filter(Q(C_Name__icontains=res1) | Q(C_Name__icontains=res2))
            elif compare(result,r6):
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='river',Popularity__gt='3')
            elif compare(result,r7):
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='river')
            elif compare(result,r8):
                res1 = q.get_tag_name('D')
                Place_Name = PlaceDetail.objects.filter(District__icontains=res1,C_Name__icontains = 'river')
            elif compare(result, r10) or compare(result,r12):
                res1 = q.get_tag_name('D')
                Place_Name= PlaceDetail.objects.filter(District__icontains=res1,C_Name__icontains='lake')
            elif compare(result,r9):
                Place_Name =  PlaceDetail.objects.filter( C_Name__icontains='lake',Popularity__gt='3')
            elif compare(result, r11):
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='lake')
            elif compare(result,r13):
                res1 = q.get_tag_name('NE')
                Place_Name = PlaceDetail.objects.filter(Name__icontains=res1)
            elif compare(result, r14):
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='National Park',Popularity__gt='2')
            elif compare(result,r15) or compare (result,r16):
                res1 = q.get_tag_name('D')
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='National Park',District__icontains=res1)
            elif compare(result,r17) or compare(result,['H','PA']):
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='National Park')
            elif compare(result,r19) or compare(result,r20) or compare(result,r22) or compare(result,['F','PV','HU']):
                res1 = q.get_tag_name('HU')
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains=res1)
            elif compare(result,r18) or compare(result,r21) or compare(result,r23):
                res1 = q.get_tag_name('D')
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='hunt',District__icontains=res1)
            elif compare(result, r24) or compare(result, r25) or compare(result,['PV','C','N']):
                Place_Name = PlaceDetail.objects.filter(C_Name__icontains='mountain',Popularity__gt='1')
            elif compare(result, r26) or compare(result, r27) or compare(result,r28) or compare(result,['PV','C','D']):

Query/templates/Query/base.html
  {% load staticfiles %}
  {% load cloudinary %}
  {% load bootstrap4 %}
  <!DOCTYPE html>
  <html lang="en">

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">
      <title>Travel</title>

      <!-- Bootstrap core CSS -->
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/index.css' %}" rel="stylesheet">
     <link href="{% static 'css/ad_ajax.css' %}" rel="stylesheet">
  </head>

  <body id="body" >

      <!-- sign in form  -->
     
            <div class="row">
              <div class="col">

                <!-- Modal-->
                    <div class="modal fade" id="Sign_In_Modal" role="dialog">
                    <div class="modal-dialog ">

                      <!-- Modal content-->
                      <div class="modal-content" style=" background-color: #e8e6ef; padding: 10px; margin: auto; width: 130%; border: 1px solid #767b7f; border-radius:3%;">
                        <div class="modal-header" style="color: black;"> Explore our recommendations and write your own blogs. </div>
                          
                          <!-- corousel in sign in modal -->
                          <div class="container">
                              <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                                <div class="carousel-inner">
                                  <div class="carousel-item active">
                                    <img class="d-block" src="/media/restaurant/Dalle.png" style=" border: 3px solid #767b7f; border-radius: 2%; margin: auto; height: 300px; width:auto;" alt="First slide">
                                  </div>
                                  <div class="carousel-item">
                                    <img class="d-block" src="/media/restaurant/OR2K.jpg" style=" border: 3px solid #767b7f; border-radius: 2%;  margin:auto; height: 300px; width:auto;" alt="Second slide">
                                  </div>
                                  <div class="carousel-item">
                                    <img class="d-block" src="/media/restaurant/Melrose_Restaurant___Bar.jpg" style=" border: 3px solid #767b7f; border-radius: 2%;  margin: auto; height: 300px; width:auto;" alt="Third slide">
                                  </div>
                                </div>
                                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                  <span class="sr-only">Previous</span>
                                </a>
                                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                  <span class="sr-only">Next</span>
                                </a>
                              </div>
                          </div>
                            <!-- corousel ends here -->
                            <hr>
                          <form method="POST" action="{% url 'Query:login'%}">
                             {% csrf_token %}
                            <div class="form-group container">
                              <label style="color: black;">Username</label>
                              <input type="text" name="username" style="color: black;" class="form-control" id="username" aria-describedby="help" placeholder="Enter username">
                              <small id="help" class="form-text text-muted">That's a good one.</small>
                            </div>
                            
                            <div class="form-group container">
                              <label style="color: black;">Password</label>
                              <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                            </div>
                            <button type="submit" class="btn btn-success container">Okay Go!</button>
                          </form>
                          <a href="#" data-dismiss="modal" style="margin:auto; padding: 10px; float=center; color: #06599e;">No thanks!</a>
                      </div>
                    </div>
                </div>
              </div>
          </div>
      
      <!-- end of sign in form  -->




      <!-- nav bar start -->

      {% if map is None %}
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top ">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
              <div class="row container-fluid">
                <div class="col-md-2 d-flex justify-content-left">
                   <i style="color: white;font-family:cursive; font-style: oblique 70deg; font-size:16pt">Smart Travel</i>
                </div>
                  <div class="col-md-6 d-flex justify-content-center">
                    
                      <!-- Query type here -->
                      <form class="form-inline " method="get" action="{% url 'Query:result' %}" id="searchform">
                        <div class="form-row">
                            <div class="input-group input-group-lg">
                              <div class="input-group-prepend">
                                <span class="input-group-text" id="inputGroup-sizing-lg">Search: </span>
                              </div>
                              <input type="text" class="form-control" id="suggestion" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="place" placeholder="Type Query">
                            </div>
                        </div>
                      </form>
                      <!-- Qeuery ends here -->
                  </div>
                 
                  <div class="col-md-4">
                      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                        <li class="nav-item">
                          {% if user.is_authenticated %}
                              <a class="nav-link"  href="{% url 'Query:home' %}"><b>Home</b></a><!-- back to blog/index.html page-->
                          {% else %}
                           <a class="nav-link"  href="{% url 'Query:login' %}"><b>Home</b></a><!-- back to blog/index.html page-->
                          </li>
                          {% endif %}
                          

                         <li class="nav-item">
                              <a class="nav-link"  href="/map/"><b>Map</b></a><!-- back to blog/index.html page-->
                          </li>
                          <div class="col-md-2">
                      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                         <li class="nav-item">
                              <a class="nav-link" href="{% url 'Blog:index' %}"><b>Blog</b></a><!-- back to blog/index.html page-->
                          </li>


                     {% if not user.is_authenticated %}
                          <li class="nav-item">
                              <a class="nav-link" href="{% url 'Query:register' %}"><b>SignUp</b></a><!-- back to blog/index.html page-->
                          </li>
                          <li class="nav-item"><button type="button" href="" class="btn btn-outline-secondary" data-toggle="modal" data-target="#Sign_In_Modal">SignIn</button>
                          </li>
                      
                      {% else %}
                        <li class="nav-item active">
                              <a class="nav-link" href="{% url 'Query:logout' %}"><b>LogOut</b></a><!-- back to blog/index.html page-->
                          </li>
                      
                      {% endif %}
                      </ul>
                  </div>
              </div>
          </div>
      </nav>
    {% endif %}
        
        <div style="margin-top:1%; padding: 20px;">
          {% block detail_content %} {% endblock %}
          {% block rec_content %}{% endblock %}
          {% block result_content %} {% endblock %}
           
        </div>
        <div style="margin:1%; padding: 2px; color:black;">
          {% block map_content %}{% endblock %} 
        </div>
        

    <script src="{% static 'js/sumit.js' %}"></script>



  <div class="modal fade" id="MailUs" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
    <div class="modal-dialog" role="document">
      <div class="modal-content"  style="padding: none; margin: none; color: black;">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"  style="padding: none; margin: none; color: black;"> Any Queries? </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="recipient-name" class="col-form-label"  style="padding: none; margin: none; color: black;">Subject:</label>
              <input type="text" class="form-control" id="recipient-name">
            </div>
            <div class="form-group">
              <label for="message-text" class="col-form-label"  style="padding: none; margin: none; color: black;">Description:</label>
              <textarea class="form-control" id="message-text"></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"  style="padding: none; margin: none; color: white;">Close</button>
          <button type="submit" class="btn btn-primary" data-dismiss="modal"  style="padding: none; margin: none; color: white;">Send message</button>
        </div>
      </div>
    </div>
  </div>
   

   <!-- Footer -->
      <footer class="py-3 bg-dark" style="padding: none; margin: none; color: black;">
        <div class="container">
          <div class="row">        
            <div class="col-md-6">
              <ul class="navbar-nav">
               <li class="nav-item">
                    <a href="#" style="text-decoration:none;">About US</a>
                </li>
                <li class="nav-item">
                    <a href="#"> Contact Us</a>
                </li>
                <li class="nav-item">
                  <a href="#" style="text-decoration:none;">Terms  &copy; Policies </a>
                </li>
              </ul>
              
          </div>
          <div class="col-md-3">
            <p class="m-0 d-flex text-white">Copyright &copy; Smart Travel 2018</p>
          </div>

          <div class="col-md-3">
            <!-- FAQ-->
            <div class="container" style="padding:none;">
              <div class="col-md-6" style='margin-bottom: 20px;'>
                <button type="button" class="btn btn-lg btn-secondary" data-toggle="modal" data-target="#MailUs">Mail Us</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=
AIzaSyAnJhsjQnWlaotqSeSPtWELspN4WG1sE0s&libraries=places&callback=initMap"></script>
      
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script type="text/javascript">
        $('.carousel').carousel();
      </script>

            
  </body>
  </html>

Query/templates/Query/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logout</title>
</head>
<body>
<h2> Thank you for visiting!!! </h2>
<a href="/"> Back</a>
</body>
</html>

Query/templates/Query/register.html
{%load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
	<div class="container bg-light" style="margin-top: 30px; padding-top:30px;">
	
	<div class="page-header">	
		<br>
		<h4 class="lead">Register a new account.</h4>
		<hr class="my-4">
	</div>

	<form action="{% url 'Query:register' %}" method="post" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		
		<button name="submit" class="btn btn-primary">register</button>
		<input type="hidden" name="next" value="{% url 'Query:login' %}">
	</form>
	<p>Already have an account? <a href="{% url 'Query:login' %}">Log in.</a></p>

    </div> 

</body>
</html>